[[index]]
name = "tuna"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[[index]]
name = "ustc"
url = "https://mirrors.ustc.edu.cn/pypi/web/simple"

[[index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
