[tools]
bun = "latest"
elixir = "latest"
erlang = "latest"
ffmpeg = "latest"
java = "adopt"
node = "lts"
uv = "latest"
yt-dlp = "latest"

[tool_alias.java.versions]
adopt = "adoptopenjdk-21"

[env]
ERL_AFLAGS = "-kernel shell_history enabled"
RUST_WITHOUT = "rust-docs"

[settings]
python.uv_venv_auto = true
